version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "avito"
      POSTGRES_USER: "avito"
      POSTGRES_PASSWORD: "avito"
    volumes:
      - ./init/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  golang:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:80
    links:
      - database
